#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

required_files=(
  "README.md"
  "README.ko.md"
  "AGENTS.md"
  "LICENSE"
  "VERSION"
  "CHANGELOG.md"
  ".codex-foundry/manifest.toml"
  ".github/workflows/repo-ci.yml"
  ".github/workflows/tag-ci.yml"
  ".gitignore"
  ".codex/config.example.toml"
  ".codex/config.multi-agent.example.toml"
  ".codex/agents/explorer.toml"
  ".codex/agents/reviewer.toml"
  ".codex/agents/docs-researcher.toml"
  ".codex/mcp/README.md"
  "docs/FIRST-STEPS.md"
  "docs/WORKFLOWS.md"
  "docs/CUSTOMIZATION.md"
  "docs/ADVANCED-CODEX-POWER.md"
  "docs/SETUP-DOCTOR.md"
  "docs/PROMPT-PLAYBOOKS.md"
  "docs/PROMPT-PLAYBOOKS.ko.md"
  "docs/STACK-PROFILES.md"
  "docs/UPGRADING.md"
  "docs/RELEASING.md"
  "scripts/bootstrap.sh"
  "scripts/bootstrap.ps1"
  "scripts/codex-doctor.sh"
  "scripts/codex-doctor.ps1"
  "scripts/prepare-release.sh"
  "scripts/prepare-release.ps1"
  "scripts/upgrade.sh"
  "scripts/upgrade.ps1"
  "scripts/managed-files.txt"
  "scripts/bootstrap-files.txt"
  "scripts/manifest-tools.sh"
  "tests/doctor_smoke.sh"
  "tests/profile_smoke.sh"
  "tests/release_smoke.sh"
  "tests/upgrade_smoke.sh"
  "profiles/nextjs-app-router/docs/STACK-PROFILE.md"
  "profiles/nextjs-app-router/docs/STACK-PROMPT-PLAYBOOKS.md"
  "profiles/node-api/docs/STACK-PROFILE.md"
  "profiles/node-api/docs/STACK-PROMPT-PLAYBOOKS.md"
  "profiles/python-service/docs/STACK-PROFILE.md"
  "profiles/python-service/docs/STACK-PROMPT-PLAYBOOKS.md"
)

skills=(
  "feature-design"
  "implementation-plan"
  "tdd-implement"
  "systematic-debug"
  "request-code-review"
  "verification-gate"
  "finish-branch"
  "codex-setup-check"
)

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

assert_file() {
  local path="$1"
  [[ -f "${ROOT_DIR}/${path}" ]] || fail "missing file: ${path}"
}

for file in "${required_files[@]}"; do
  assert_file "${file}"
done

grep -q "Template Repository" "${ROOT_DIR}/README.md" || fail "README missing Template Repository badge marker"
grep -q "MIT License" "${ROOT_DIR}/README.md" || fail "README missing MIT License badge marker"
grep -q "repo-ci" "${ROOT_DIR}/README.md" || fail "README missing repo-ci badge marker"
grep -q "\[Quick Start\](#start-here)" "${ROOT_DIR}/README.md" || fail "README missing quick start nav link"
grep -q "\[Workflow\](#default-workflow)" "${ROOT_DIR}/README.md" || fail "README missing workflow nav link"
grep -q "\[Docs\](#docs)" "${ROOT_DIR}/README.md" || fail "README missing docs nav link"
grep -q "\[Upgrade\](docs/UPGRADING.md)" "${ROOT_DIR}/README.md" || fail "README missing upgrade nav link"
grep -q "upstream template repo" "${ROOT_DIR}/README.md" || fail "README must warn about the upstream CI badge"
grep -q "Upgrading" "${ROOT_DIR}/README.md" || fail "README must link to Upgrading"
grep -q "Releasing" "${ROOT_DIR}/README.md" || fail "README must link to Releasing"
grep -q "repo-ci" "${ROOT_DIR}/README.ko.md" || fail "Korean README missing repo-ci badge marker"
grep -q "\[바로 시작하기\](#바로-시작하기)" "${ROOT_DIR}/README.ko.md" || fail "Korean README missing quick start nav link"
grep -q "\[워크플로우\](#기본-워크플로우)" "${ROOT_DIR}/README.ko.md" || fail "Korean README missing workflow nav link"
grep -q "\[문서\](#문서)" "${ROOT_DIR}/README.ko.md" || fail "Korean README missing docs nav link"
grep -q "\[업그레이드\](docs/UPGRADING.md)" "${ROOT_DIR}/README.ko.md" || fail "Korean README missing upgrade nav link"
grep -q "upstream 템플릿 레포용입니다" "${ROOT_DIR}/README.ko.md" || fail "Korean README must warn about the upstream CI badge"
grep -q "Upgrading" "${ROOT_DIR}/README.ko.md" || fail "Korean README must link to Upgrading"
grep -q "Releasing" "${ROOT_DIR}/README.ko.md" || fail "Korean README must link to Releasing"
grep -q "^## Template Consumers$" "${ROOT_DIR}/docs/CUSTOMIZATION.md" || fail "Customization doc must define a Template Consumers section"
grep -q "repo-ci.yml" "${ROOT_DIR}/docs/CUSTOMIZATION.md" || fail "Customization doc must mention repo-ci.yml"
grep -q "Replace or remove" "${ROOT_DIR}/docs/CUSTOMIZATION.md" || fail "Customization doc must explain the upstream CI badge handoff"
grep -q "UPGRADING.md" "${ROOT_DIR}/docs/CUSTOMIZATION.md" || fail "Customization doc must link to UPGRADING.md"
grep -q "git checkout v" "${ROOT_DIR}/docs/CUSTOMIZATION.md" || fail "Customization doc must explain tagged source checkouts"

grep -q '^0\.8\.0$' "${ROOT_DIR}/VERSION" || fail "VERSION must contain the first public version 0.8.0"
grep -q '^# Changelog$' "${ROOT_DIR}/CHANGELOG.md" || fail "CHANGELOG must start with a Changelog heading"
grep -q '^## \[Unreleased\]$' "${ROOT_DIR}/CHANGELOG.md" || fail "CHANGELOG must define an Unreleased section"
grep -q '^## \[0\.8\.0\] - 2026-03-10$' "${ROOT_DIR}/CHANGELOG.md" || fail "CHANGELOG must define the 0.8.0 release section"

grep -q 'kit = "codex-foundry"' "${ROOT_DIR}/.codex-foundry/manifest.toml" || fail "manifest must declare the codex-foundry kit"
grep -q '^manifest_version = 1$' "${ROOT_DIR}/.codex-foundry/manifest.toml" || fail "manifest must declare manifest_version = 1"
grep -q '^source_commit = "' "${ROOT_DIR}/.codex-foundry/manifest.toml" || fail "manifest must include source_commit"
grep -q '^active_profile = "' "${ROOT_DIR}/.codex-foundry/manifest.toml" || fail "manifest must include active_profile"
grep -q '^\[\[files\]\]' "${ROOT_DIR}/.codex-foundry/manifest.toml" || fail "manifest must include managed file records"
! grep -q '^source_version = ' "${ROOT_DIR}/.codex-foundry/manifest.toml" || fail "manifest v1 must not add source_version"

grep -q "^name: repo-ci$" "${ROOT_DIR}/.github/workflows/repo-ci.yml" || fail "repo-ci workflow must declare the correct name"
grep -q "^on:" "${ROOT_DIR}/.github/workflows/repo-ci.yml" || fail "repo-ci workflow must define triggers"
grep -q "push:" "${ROOT_DIR}/.github/workflows/repo-ci.yml" || fail "repo-ci workflow must run on push"
grep -q "pull_request:" "${ROOT_DIR}/.github/workflows/repo-ci.yml" || fail "repo-ci workflow must run on pull_request"
grep -q "workflow_dispatch:" "${ROOT_DIR}/.github/workflows/repo-ci.yml" || fail "repo-ci workflow must support workflow_dispatch"
grep -q "main" "${ROOT_DIR}/.github/workflows/repo-ci.yml" || fail "repo-ci workflow must target main"
grep -q "ubuntu-latest" "${ROOT_DIR}/.github/workflows/repo-ci.yml" || fail "repo-ci workflow must use ubuntu-latest"
grep -q "bash tests/validate_repo.sh" "${ROOT_DIR}/.github/workflows/repo-ci.yml" || fail "repo-ci workflow must run validate_repo.sh"
grep -q "bash tests/bootstrap_safety.sh" "${ROOT_DIR}/.github/workflows/repo-ci.yml" || fail "repo-ci workflow must run bootstrap_safety.sh"
grep -q "bash tests/profile_smoke.sh" "${ROOT_DIR}/.github/workflows/repo-ci.yml" || fail "repo-ci workflow must run profile_smoke.sh"
grep -q "bash tests/doctor_smoke.sh" "${ROOT_DIR}/.github/workflows/repo-ci.yml" || fail "repo-ci workflow must run doctor_smoke.sh"
grep -q "bash tests/release_smoke.sh" "${ROOT_DIR}/.github/workflows/repo-ci.yml" || fail "repo-ci workflow must run release_smoke.sh"
grep -q "bash tests/upgrade_smoke.sh" "${ROOT_DIR}/.github/workflows/repo-ci.yml" || fail "repo-ci workflow must run upgrade_smoke.sh"

grep -q "^name: tag-ci$" "${ROOT_DIR}/.github/workflows/tag-ci.yml" || fail "tag-ci workflow must declare the correct name"
grep -q "tags:" "${ROOT_DIR}/.github/workflows/tag-ci.yml" || fail "tag-ci workflow must define tag triggers"
grep -q "v\\*" "${ROOT_DIR}/.github/workflows/tag-ci.yml" || fail "tag-ci workflow must target v* tags"
grep -q "ubuntu-latest" "${ROOT_DIR}/.github/workflows/tag-ci.yml" || fail "tag-ci workflow must use ubuntu-latest"
grep -q "bash tests/validate_repo.sh" "${ROOT_DIR}/.github/workflows/tag-ci.yml" || fail "tag-ci workflow must run validate_repo.sh"
grep -q "bash tests/bootstrap_safety.sh" "${ROOT_DIR}/.github/workflows/tag-ci.yml" || fail "tag-ci workflow must run bootstrap_safety.sh"
grep -q "bash tests/profile_smoke.sh" "${ROOT_DIR}/.github/workflows/tag-ci.yml" || fail "tag-ci workflow must run profile_smoke.sh"
grep -q "bash tests/doctor_smoke.sh" "${ROOT_DIR}/.github/workflows/tag-ci.yml" || fail "tag-ci workflow must run doctor_smoke.sh"
grep -q "bash tests/release_smoke.sh" "${ROOT_DIR}/.github/workflows/tag-ci.yml" || fail "tag-ci workflow must run release_smoke.sh"
grep -q "bash tests/upgrade_smoke.sh" "${ROOT_DIR}/.github/workflows/tag-ci.yml" || fail "tag-ci workflow must run upgrade_smoke.sh"

for skill in "${skills[@]}"; do
  skill_file="${ROOT_DIR}/.agents/skills/${skill}/SKILL.md"
  [[ -f "${skill_file}" ]] || fail "missing skill: ${skill}"
  grep -q "^name: ${skill}$" "${skill_file}" || fail "missing or wrong name frontmatter in ${skill}"
  grep -q "^description: " "${skill_file}" || fail "missing description frontmatter in ${skill}"
  meta_file="${ROOT_DIR}/.agents/skills/${skill}/agents/openai.yaml"
  [[ -f "${meta_file}" ]] || fail "missing skill metadata: ${skill}"
  grep -q "display_name:" "${meta_file}" || fail "missing display_name in ${skill} metadata"
  grep -q "short_description:" "${meta_file}" || fail "missing short_description in ${skill} metadata"
  grep -q "default_prompt:" "${meta_file}" || fail "missing default_prompt in ${skill} metadata"
done

grep -q "openaiDeveloperDocs" "${ROOT_DIR}/.codex/config.example.toml" || fail "config example must mention openaiDeveloperDocs"
grep -q "context7" "${ROOT_DIR}/.codex/config.example.toml" || fail "config example must mention context7"
grep -q "features.multi_agent = true" "${ROOT_DIR}/.codex/config.multi-agent.example.toml" || fail "multi-agent example must enable features.multi_agent"
grep -q "\\[agents\\.explorer\\]" "${ROOT_DIR}/.codex/config.multi-agent.example.toml" || fail "multi-agent example must define explorer"
grep -q "\\[agents\\.reviewer\\]" "${ROOT_DIR}/.codex/config.multi-agent.example.toml" || fail "multi-agent example must define reviewer"
grep -q "\\[agents\\.docs_researcher\\]" "${ROOT_DIR}/.codex/config.multi-agent.example.toml" || fail "multi-agent example must define docs_researcher"
grep -q "config_file = \"agents/explorer.toml\"" "${ROOT_DIR}/.codex/config.multi-agent.example.toml" || fail "multi-agent example must reference explorer config"
grep -q "config_file = \"agents/reviewer.toml\"" "${ROOT_DIR}/.codex/config.multi-agent.example.toml" || fail "multi-agent example must reference reviewer config"
grep -q "config_file = \"agents/docs-researcher.toml\"" "${ROOT_DIR}/.codex/config.multi-agent.example.toml" || fail "multi-agent example must reference docs researcher config"

for skill in "${skills[@]}"; do
  grep -q "\`${skill}\`" "${ROOT_DIR}/README.md" || fail "README missing skill reference: ${skill}"
  grep -q "\`${skill}\`" "${ROOT_DIR}/docs/WORKFLOWS.md" || fail "WORKFLOWS missing skill reference: ${skill}"
done

grep -q "Advanced Codex Power" "${ROOT_DIR}/README.md" || fail "README missing Advanced Codex Power section"
grep -q "고급 Codex 기능" "${ROOT_DIR}/README.ko.md" || fail "Korean README missing advanced power section"
grep -q "multi-agent" "${ROOT_DIR}/docs/ADVANCED-CODEX-POWER.md" || fail "advanced power doc must describe multi-agent usage"
grep -q "^## What It Is$" "${ROOT_DIR}/README.md" || fail "README missing What It Is section"
grep -q "^## Start Here$" "${ROOT_DIR}/README.md" || fail "README missing Start Here section"
grep -q "^## Default Workflow$" "${ROOT_DIR}/README.md" || fail "README missing Default Workflow section"
grep -q "^## What's Included$" "${ROOT_DIR}/README.md" || fail "README missing What's Included section"
grep -q "^## Docs$" "${ROOT_DIR}/README.md" || fail "README missing Docs section"
grep -q "bash scripts/codex-doctor.sh" "${ROOT_DIR}/README.md" || fail "README must mention the shell doctor entrypoint"
grep -q "^## 이 프로젝트는 무엇인가$" "${ROOT_DIR}/README.ko.md" || fail "Korean README missing project intro section"
grep -q "^## 바로 시작하기$" "${ROOT_DIR}/README.ko.md" || fail "Korean README missing quick start section"
grep -q "^## 기본 워크플로우$" "${ROOT_DIR}/README.ko.md" || fail "Korean README missing workflow section"
grep -q "^## 포함 내용$" "${ROOT_DIR}/README.ko.md" || fail "Korean README missing included items section"
grep -q "^## 문서$" "${ROOT_DIR}/README.ko.md" || fail "Korean README missing docs section"
grep -q "Use this template" "${ROOT_DIR}/README.md" || fail "README must mention Use this template"
grep -q "bootstrap.sh" "${ROOT_DIR}/README.md" || fail "README must mention bootstrap.sh"
grep -Fq '$codex-setup-check' "${ROOT_DIR}/README.md" || fail 'README must mention $codex-setup-check'
grep -q "bootstrap.sh" "${ROOT_DIR}/README.ko.md" || fail "Korean README must mention bootstrap.sh"
grep -Fq '$codex-setup-check' "${ROOT_DIR}/README.ko.md" || fail 'Korean README must mention $codex-setup-check'
grep -q -- "--profile" "${ROOT_DIR}/README.md" || fail "README must mention --profile"
grep -q -- "--profile" "${ROOT_DIR}/README.ko.md" || fail "Korean README must mention --profile"
grep -q "bash scripts/codex-doctor.sh" "${ROOT_DIR}/docs/FIRST-STEPS.md" || fail "First Steps must mention the shell doctor command"
grep -q "pwsh -File scripts/codex-doctor.ps1" "${ROOT_DIR}/docs/FIRST-STEPS.md" || fail "First Steps must mention the PowerShell doctor command"
! grep -q "Claude Forge Translation" "${ROOT_DIR}/README.md" || fail "README should not contain Claude Forge Translation section"
! grep -q "Claude Forge 방식과의 대응" "${ROOT_DIR}/README.ko.md" || fail "Korean README should not contain Claude Forge comparison section"
! grep -q "Repository Layout" "${ROOT_DIR}/README.md" || fail "README should not contain Repository Layout section"
! grep -q "저장소 구조" "${ROOT_DIR}/README.ko.md" || fail "Korean README should not contain repository layout section"
! grep -q "^## Verification$" "${ROOT_DIR}/README.md" || fail "README should not keep a Verification section"
! grep -q "^## 검증$" "${ROOT_DIR}/README.ko.md" || fail "Korean README should not keep a Verification section"
grep -q "PASS / WARN / FAIL" "${ROOT_DIR}/docs/SETUP-DOCTOR.md" || fail "Setup Doctor doc must explain PASS / WARN / FAIL"
grep -q "/debug-config" "${ROOT_DIR}/docs/SETUP-DOCTOR.md" || fail "Setup Doctor doc must mention /debug-config"
grep -q "/mcp" "${ROOT_DIR}/docs/SETUP-DOCTOR.md" || fail "Setup Doctor doc must mention /mcp"
grep -q "/status" "${ROOT_DIR}/docs/SETUP-DOCTOR.md" || fail "Setup Doctor doc must mention /status"
grep -q "^## Bootstrap Playbook$" "${ROOT_DIR}/docs/PROMPT-PLAYBOOKS.md" || fail "Prompt Playbooks doc must define Bootstrap Playbook"
grep -q "^## Feature Playbook$" "${ROOT_DIR}/docs/PROMPT-PLAYBOOKS.md" || fail "Prompt Playbooks doc must define Feature Playbook"
grep -q "^## Bugfix Playbook$" "${ROOT_DIR}/docs/PROMPT-PLAYBOOKS.md" || fail "Prompt Playbooks doc must define Bugfix Playbook"
grep -q "^## Bootstrap Playbook$" "${ROOT_DIR}/docs/PROMPT-PLAYBOOKS.ko.md" || fail "Korean Prompt Playbooks doc must define Bootstrap Playbook"
grep -q "^## Feature Playbook$" "${ROOT_DIR}/docs/PROMPT-PLAYBOOKS.ko.md" || fail "Korean Prompt Playbooks doc must define Feature Playbook"
grep -q "^## Bugfix Playbook$" "${ROOT_DIR}/docs/PROMPT-PLAYBOOKS.ko.md" || fail "Korean Prompt Playbooks doc must define Bugfix Playbook"
grep -q "bash scripts/codex-doctor.sh" "${ROOT_DIR}/docs/PROMPT-PLAYBOOKS.md" || fail "Prompt Playbooks doc must mention the shell doctor command"
grep -q "pwsh -File scripts/codex-doctor.ps1" "${ROOT_DIR}/docs/PROMPT-PLAYBOOKS.md" || fail "Prompt Playbooks doc must mention the PowerShell doctor command"
grep -q "\`feature-design\`" "${ROOT_DIR}/docs/PROMPT-PLAYBOOKS.md" || fail "Prompt Playbooks doc must mention feature-design"
grep -q "\`systematic-debug\`" "${ROOT_DIR}/docs/PROMPT-PLAYBOOKS.md" || fail "Prompt Playbooks doc must mention systematic-debug"
grep -q "Prompt Playbooks" "${ROOT_DIR}/README.md" || fail "README must link to Prompt Playbooks"
grep -q "Prompt Playbooks" "${ROOT_DIR}/README.ko.md" || fail "Korean README must link to Prompt Playbooks"
grep -q "Prompt Playbooks" "${ROOT_DIR}/docs/FIRST-STEPS.md" || fail "First Steps must link to Prompt Playbooks"
grep -q "Prompt Playbooks" "${ROOT_DIR}/docs/WORKFLOWS.md" || fail "Workflows must link to Prompt Playbooks"
grep -q "Stack Profiles" "${ROOT_DIR}/README.md" || fail "README must link to Stack Profiles"
grep -q "Stack Profiles" "${ROOT_DIR}/README.ko.md" || fail "Korean README must link to Stack Profiles"
grep -q "Stack Profiles" "${ROOT_DIR}/docs/FIRST-STEPS.md" || fail "First Steps must mention Stack Profiles"
grep -q -- "--profile" "${ROOT_DIR}/docs/STACK-PROFILES.md" || fail "Stack Profiles doc must mention --profile"
grep -q "^## Supported Profiles$" "${ROOT_DIR}/docs/STACK-PROFILES.md" || fail "Stack Profiles doc must define Supported Profiles"
grep -q "nextjs-app-router" "${ROOT_DIR}/docs/STACK-PROFILES.md" || fail "Stack Profiles doc must mention nextjs-app-router"
grep -q "node-api" "${ROOT_DIR}/docs/STACK-PROFILES.md" || fail "Stack Profiles doc must mention node-api"
grep -q "python-service" "${ROOT_DIR}/docs/STACK-PROFILES.md" || fail "Stack Profiles doc must mention python-service"
grep -q "docs/STACK-PROFILE.md" "${ROOT_DIR}/AGENTS.md" || fail "AGENTS must mention the optional stack profile overlay"
grep -q "docs/STACK-PROFILE.md" "${ROOT_DIR}/.agents/skills/feature-design/SKILL.md" || fail "feature-design must mention the optional stack profile overlay"
grep -q "docs/STACK-PROFILE.md" "${ROOT_DIR}/.agents/skills/implementation-plan/SKILL.md" || fail "implementation-plan must mention the optional stack profile overlay"
grep -q "docs/STACK-PROFILE.md" "${ROOT_DIR}/.agents/skills/tdd-implement/SKILL.md" || fail "tdd-implement must mention the optional stack profile overlay"
grep -q "docs/STACK-PROFILE.md" "${ROOT_DIR}/.agents/skills/systematic-debug/SKILL.md" || fail "systematic-debug must mention the optional stack profile overlay"
grep -q "docs/STACK-PROFILE.md" "${ROOT_DIR}/.agents/skills/verification-gate/SKILL.md" || fail "verification-gate must mention the optional stack profile overlay"
grep -q "docs/STACK-PROFILE.md" "${ROOT_DIR}/.agents/skills/codex-setup-check/SKILL.md" || fail "codex-setup-check must mention the optional stack profile overlay"
grep -q "scripts/codex-doctor.sh" "${ROOT_DIR}/.agents/skills/codex-setup-check/SKILL.md" || fail "codex-setup-check must point users to the shell doctor"
grep -q "scripts/upgrade.sh" "${ROOT_DIR}/.agents/skills/codex-setup-check/SKILL.md" || fail "codex-setup-check must mention the upgrade path"
grep -q "Profile ID: nextjs-app-router" "${ROOT_DIR}/profiles/nextjs-app-router/docs/STACK-PROFILE.md" || fail "nextjs profile doc must declare its profile id"
grep -q "Profile ID: node-api" "${ROOT_DIR}/profiles/node-api/docs/STACK-PROFILE.md" || fail "node profile doc must declare its profile id"
grep -q "Profile ID: python-service" "${ROOT_DIR}/profiles/python-service/docs/STACK-PROFILE.md" || fail "python profile doc must declare its profile id"
grep -q "## Bootstrap Playbook" "${ROOT_DIR}/profiles/nextjs-app-router/docs/STACK-PROMPT-PLAYBOOKS.md" || fail "nextjs prompt playbooks must define Bootstrap Playbook"
grep -q "## Feature Playbook" "${ROOT_DIR}/profiles/node-api/docs/STACK-PROMPT-PLAYBOOKS.md" || fail "node prompt playbooks must define Feature Playbook"
grep -q "## Bugfix Playbook" "${ROOT_DIR}/profiles/python-service/docs/STACK-PROMPT-PLAYBOOKS.md" || fail "python prompt playbooks must define Bugfix Playbook"
grep -q "scripts/upgrade.sh" "${ROOT_DIR}/docs/UPGRADING.md" || fail "UPGRADING doc must mention the shell upgrade entrypoint"
grep -q "scripts/upgrade.ps1" "${ROOT_DIR}/docs/UPGRADING.md" || fail "UPGRADING doc must mention the PowerShell upgrade entrypoint"
grep -q -- "--adopt" "${ROOT_DIR}/docs/UPGRADING.md" || fail "UPGRADING doc must explain --adopt"
grep -q "conflict" "${ROOT_DIR}/docs/UPGRADING.md" || fail "UPGRADING doc must explain conflict handling"
grep -q "UPGRADING.md" "${ROOT_DIR}/docs/STACK-PROFILES.md" || fail "Stack Profiles doc must link to upgrade guidance"
grep -q "UPGRADING.md" "${ROOT_DIR}/README.md" || fail "README must link to upgrade guidance"
grep -q "UPGRADING.md" "${ROOT_DIR}/README.ko.md" || fail "Korean README must link to upgrade guidance"
grep -q "RELEASING.md" "${ROOT_DIR}/README.md" || fail "README must link to releasing guidance"
grep -q "RELEASING.md" "${ROOT_DIR}/README.ko.md" || fail "Korean README must link to releasing guidance"
grep -q "git checkout v0.8.0" "${ROOT_DIR}/docs/UPGRADING.md" || fail "UPGRADING doc must show a tagged source checkout example"
grep -q "prepare-release.sh" "${ROOT_DIR}/docs/RELEASING.md" || fail "RELEASING doc must mention the shell release entrypoint"
grep -q "prepare-release.ps1" "${ROOT_DIR}/docs/RELEASING.md" || fail "RELEASING doc must mention the PowerShell release entrypoint"
grep -q "gh release create v0.8.0 --generate-notes" "${ROOT_DIR}/docs/RELEASING.md" || fail "RELEASING doc must show the GitHub release command"
grep -q "CHANGELOG.md" "${ROOT_DIR}/docs/RELEASING.md" || fail "RELEASING doc must mention CHANGELOG.md"
grep -q "VERSION" "${ROOT_DIR}/docs/RELEASING.md" || fail "RELEASING doc must mention VERSION"
grep -q "upgrade_smoke.sh" "${ROOT_DIR}/AGENTS.md" || fail "AGENTS must mention upgrade_smoke.sh in verification guidance"
grep -q "release_smoke.sh" "${ROOT_DIR}/AGENTS.md" || fail "AGENTS must mention release_smoke.sh in verification guidance"
grep -q "upgrade_smoke.sh" "${ROOT_DIR}/.agents/skills/verification-gate/SKILL.md" || fail "verification-gate must mention upgrade_smoke.sh"
grep -q "release_smoke.sh" "${ROOT_DIR}/.agents/skills/verification-gate/SKILL.md" || fail "verification-gate must mention release_smoke.sh"
grep -q "scripts/upgrade.sh" "${ROOT_DIR}/scripts/codex-doctor.sh" || fail "shell doctor must mention the upgrade path"
grep -q "scripts/upgrade.ps1" "${ROOT_DIR}/scripts/codex-doctor.ps1" || fail "PowerShell doctor must mention the upgrade path"
grep -q ".codex-foundry/manifest.toml" "${ROOT_DIR}/scripts/codex-doctor.sh" || fail "shell doctor must validate the manifest"
grep -q ".codex-foundry/manifest.toml" "${ROOT_DIR}/scripts/codex-doctor.ps1" || fail "PowerShell doctor must validate the manifest"
grep -q ".codex-foundry/manifest.toml" "${ROOT_DIR}/scripts/bootstrap.sh" || fail "bootstrap must write the managed manifest"
grep -q ".codex-foundry/manifest.toml" "${ROOT_DIR}/scripts/bootstrap.ps1" || fail "PowerShell bootstrap must write the managed manifest"
grep -q "scripts/upgrade.sh" "${ROOT_DIR}/scripts/bootstrap.sh" || fail "bootstrap must copy the shell upgrade script"
grep -q "scripts/upgrade.ps1" "${ROOT_DIR}/scripts/bootstrap.ps1" || fail "PowerShell bootstrap must copy the PowerShell upgrade script"
grep -q "manifest-tools.sh" "${ROOT_DIR}/scripts/bootstrap.sh" || fail "bootstrap must use manifest tooling"
grep -q "manifest-tools.sh" "${ROOT_DIR}/scripts/upgrade.sh" || fail "upgrade must use manifest tooling"
grep -q "prepare-release.sh" "${ROOT_DIR}/scripts/prepare-release.sh" || fail "prepare-release.sh should describe its own entrypoint"
grep -q "git tag v" "${ROOT_DIR}/scripts/prepare-release.sh" || fail "prepare-release.sh must print tag commands"
grep -q "gh release create v" "${ROOT_DIR}/scripts/prepare-release.sh" || fail "prepare-release.sh must print release commands"

if compgen -G "${ROOT_DIR}/.agents/skills/*/agents/openai.yaml" > /dev/null; then
  while IFS= read -r yaml_file; do
    grep -q ":" "${yaml_file}" || fail "invalid openai.yaml (no mapping): ${yaml_file}"
  done < <(find "${ROOT_DIR}/.agents/skills" -path "*/agents/openai.yaml" -type f | sort)
fi

echo "validate_repo.sh: OK"
